### ISSUE TITLE
Determine if payment has been made for entry

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/fwfballot#14]
1. Some hunters will THINK they are in but haven’t paid and so aren’t (although I guess they really ARE currently since there’s no link between entry and 'paid' at the moment) … so:
2. A report Russell might need is “entered but not paid” I guess and a way of emailing those that haven’t. Maybe part of the messages area…
3. This will also be needed to draw only those who've paid
4. Currently also possible for a hunter to only pay for ONE member of the party... thereby invalidating the rest of the entry

**Comment by norwegianblue-nz** [comment]
Report tabs added to the Orders page
