### ISSUE TITLE
Page title /manage/all_allocations and /manage/unconfirmed_entries

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/fwfballot#30]
Think these 2 pages were re-purposed views? Both have incorrect tiles. (Both have "Withdrawn Allocations").
Should be "All Block Allocations" and "Unconfirmed Allocations" (or something similar).

You can assign to me if you're happy with that (and I can do it of course!)

**Comment by norwegianblue-nz** [comment]
Fixed
